version: "3.8"

services:
  christian-app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: christian-app
    volumes:
      - ./:/app
    ports:
      - 5173:5173
      - 4173:4173
    tty: true
